- name: Install Default Software
  tasks:
    - name: Install Firefox
      win_chocolatey:
        name: firefox
        state: present
    - name: Install Notepad++
      win_chocolatey:
        name: notepadplusplus
        state: present
    - name: Install PowerToys
        name: powertoys
        state: present
